###
# List gauges
POST http://localhost:7080/upstream/nz_waikato/gauges
Cache-Control: no-cache
Content-Type: application/json

###
# Harvest measurements
POST http://localhost:7080/upstream/nz_waikato/measurements
Cache-Control: no-cache
Content-Type: application/json

###