# List gauges
POST http://localhost:7080/upstream/riverzone/gauges
Cache-Control: no-cache
Content-Type: application/json

###
# Get measurements
POST http://localhost:7080/upstream/riverzone/measurements
Cache-Control: no-cache
Content-Type: application/json

###
# Original V1 endpoint
GET https://api.riverzone.eu/v1/stations?status=enabled
X-Key: {{$processEnv %RIVERZONE_KEY}}

###
# Stations V2 endpoint
GET https://api.riverzone.eu/v2/stations
X-Key: {{$processEnv %RIVERZONE_KEY}}

###
# Readings V2 endpoint
GET https://api.riverzone.eu/v2/stations/readings?from=60&to=60
X-Key: {{$processEnv %RIVERZONE_KEY}}
