package riverzone

// Mapping between european countries and timezones
// generated with https://www.npmjs.com/package/countries-and-timezones and refined manually
var rzTz = map[string]string{
	"AD": "Europe/Andorra",
	"AL": "Europe/Tirane",
	"AT": "Europe/Vienna",
	"AX": "Europe/Mariehamn",
	"BA": "Europe/Sarajevo",
	"BE": "Europe/Brussels",
	"BG": "Europe/Sofia",
	"BV": "Europe/Oslo",
	"BY": "Europe/Minsk",
	"CH": "Europe/Zurich",
	"CY": "Europe/Nicosia",
	"CZ": "Europe/Prague",
	"DE": "Europe/Berlin",
	"DK": "Europe/Copenhagen",
	"EE": "Europe/Tallinn",
	"ES": "Europe/Madrid",
	"FI": "Europe/Helsinki",
	"FR": "Europe/Paris",
	"GB": "Europe/London",
	"GG": "Europe/Guernsey",
	"GI": "Europe/Gibraltar",
	"GR": "Europe/Athens",
	"HR": "Europe/Zagreb",
	"HU": "Europe/Budapest",
	"IE": "Europe/Dublin",
	"IM": "Europe/Isle_of_Man",
	"IT": "Europe/Rome",
	"JE": "Europe/Jersey",
	"LI": "Europe/Vaduz",
	"LT": "Europe/Vilnius",
	"LU": "Europe/Luxembourg",
	"LV": "Europe/Riga",
	"MC": "Europe/Monaco",
	"MD": "Europe/Chisinau",
	"ME": "Europe/Podgorica",
	"MK": "Europe/Skopje",
	"MT": "Europe/Malta",
	"NL": "Europe/Amsterdam",
	"NO": "Europe/Oslo",
	"PL": "Europe/Warsaw",
	"PT": "Europe/Lisbon",
	"RO": "Europe/Bucharest",
	"RS": "Europe/Belgrade",
	"SE": "Europe/Stockholm",
	"SI": "Europe/Ljubljana",
	"SK": "Europe/Bratislava",
	"SM": "Europe/San_Marino",
	"TR": "Europe/Istanbul",
	"UA": "Europe/Kiev",
	"VA": "Europe/Vatican",
}
