version: "3.7"

services:
  app:
    build:
      context: .
      target: development
    image: gorge-dev
    container_name: gorge-dev
    ports:
      - "5080:7080"
    env_file: .env.development
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/workspace:cached
      - mitmcerts:/usr/share/ca-certificates/mitmproxy
    command: /bin/sh -c "while sleep 1000; do :; done"

  mitm:
    image: mitmproxy/mitmproxy
    container_name: mitm
    command: mitmweb --web-host 0.0.0.0 --showhost
    ports:
      - 6080:8080
      - 6081:8081
    tty: true
    stdin_open: true
    volumes:
      - mitmcerts:/home/mitmproxy/.mitmproxy

volumes:
  mitmcerts:
