###
# List gauges
POST http://localhost:7080/upstream/cantabria/gauges
Cache-Control: no-cache
Content-Type: application/json

###
# List all measurements
POST http://localhost:7080/upstream/cantabria/measurements
Cache-Control: no-cache
Content-Type: application/json

###
