###
# List gauges
POST http://localhost:7080/upstream/quebec2/gauges
Cache-Control: no-cache
Content-Type: application/json

###
# Harvest measurements
POST http://localhost:7080/upstream/quebec2/measurements
Cache-Control: no-cache
Content-Type: application/json

###