# List gauges
POST http://localhost:7080/upstream/sepa/gauges
Cache-Control: no-cache
Content-Type: application/json

###
# Get measurements
POST http://localhost:7080/upstream/sepa/measurements?codes=14870
Cache-Control: no-cache
Content-Type: application/json

###
