###
# List gauges
POST http://localhost:7080/upstream/ukea/gauges
Cache-Control: no-cache
Content-Type: application/json

###
# Get measurements
POST http://localhost:7080/upstream/ukea/measurements
Cache-Control: no-cache
Content-Type: application/json

###
