###
# List gauges
POST http://localhost:7080/upstream/nzstl/gauges
Cache-Control: no-cache
Content-Type: application/json

###
# Harvest measurements
POST http://localhost:7080/upstream/nzstl/measurements
Cache-Control: no-cache
Content-Type: application/json

###